### ISSUE TITLE
feature request: richtextfield

### ISSUE THREAD

**Issue by onno-timmerman** [wagtail/wagtail-localize#280] opened 2020-12-08 12:39 UTC
When you have translate a richtextfield the translator is expected to translate this in raw html. This will give problems. Maybe better to use the same richtextfield as the orignal document.

**Comment by codingcatgirl** [comment] 2020-12-14 14:33
That's not really how the rich text translation works in the version i have? It gets split into paragraphs. Having a minor amount of html in translation files for links or emphasis is pretty much standard.

**Comment by kaedroho** [comment] 2020-12-15 18:36
This looks like a duplicate of: https://github.com/wagtail/wagtail-localize/issues/261

We need to split it up by paragraph so that minor edits to rich text fields don't require them to be retranslated from scratch. Also, Wagtail Localize is designed to work with external translation systems and PO files which mostly don't have rich text editors. So the other reason for splitting up into paragraphs is to simplify the HTML that needs to be translated (it removes the need for translators to work with Wagtail's custom block tags for images, embeds, etc).

**Closed by kaedroho** 2020-12-15 18:36 UTC

**Comment by helderco** [comment] 2021-03-24 10:25
@kaedroho What about having a richtext field in translation that only supports inline tags such as `<b>`, then same ones that aren't extracted from source? My client won't even know what that tag is and I think this just provides a better UX when translating on site, but still supporting everything else as it is.
