### ISSUE TITLE
The configuration instructions are a bit confusing

### ISSUE THREAD

**Issue by fab10m** [wagtail/wagtail-localize#315] opened 2021-02-02 10:04 UTC
Hi,

imho the configuration instructions are a bit confusing where you write
```python 
"wagtail_localize.locales",  # Note: This replaces "wagtail.locales"
```
If I follow your instructions, when I try to add a Locale I'm forced to translate all the contents. Instead, if I follow the instructions of the [official documentation of wagtail](https://docs.wagtail.io/en/stable/advanced_topics/i18n.html) and use "wagtail.locales", I was able to add a Locale without having to translate all the contents at once.

Fabio

**Comment by patillacode** [comment] 2021-02-02 12:59
I agree, using the `wagtail_localize.locales` forces to translate the whole content.
I also had to use `wagtail.locales` instead to avoid that and do a one-by-one translation.

Is this the intended behaviour?
What are we missing when using one or the other?

**Comment by kaedroho** [comment] 2021-02-02 13:25
The ``wagtail_localize.locales`` module is just a stop-gap until https://github.com/wagtail/wagtail/pull/6398 is merged into Wagtail core. After that is merged, you can switch back to Wagtail core's locale module.

The difference is that ``wagtail_localize.locales`` provides a "Sync from" field that allows you to copy initial content from one locale to another. This is useful for sites that only want to translate specific content but fall back to another language for the rest. This shouldn't be forcing you to translate everything, it merely creates alias pages for the content so that you don't have to translate everything in order to get a usable site. But if you don't want this behaviour, you can leave that field blank.

**Comment by patillacode** [comment] 2021-02-02 14:21
Thanks for the quick response.

I understand the stop-gap approach but the `Sync from` field is mandatory, therefore I can only create a locale using `'wagtail_localize.locales'` in my `INSTALLED_APPS` if I translate all my existing pages when doing so. 
That is why I said we are _forced_, see screenshot below:

![Screenshot 2021-02-02 at 15 19 05](https://user-images.githubusercontent.com/10074977/106613028-08973c80-656a-11eb-8e11-f7a6877799ed.png)

Maybe I should raise this in another ticket, please let me know if that is the case.

**Comment by kaedroho** [comment] 2021-02-02 14:34
Oh, yep that should be optional. Please raise a ticket for that, thanks!

**Comment by patillacode** [comment] 2021-02-02 17:34
Issue has been created, I would say we can close this one now.

**Comment by kaedroho** [comment] 2021-02-12 10:55
Thanks!

**Closed by kaedroho** 2021-02-12 10:55 UTC
