### ISSUE TITLE
Option to translate a StreamField with a ListBlock doesn't show

### ISSUE THREAD

**Issue by MrCordeiro** [wagtail/wagtail-localize#323] opened 2021-02-12 10:55 UTC
Hello, I wanted to know if the following is a package limitation or if I messed up with the setup.

I'm trying to translate an existing project and the Pricing page is giving me trouble. There, I have 3 fields: `title`, `subtitle`, and pricing `plans`. The first two work fine, while the latter doesn't even show to be translated at the admin.

Here's how the `plan` field's been defined:

```
# models.py, inside the PricingPage class
plans = StreamField(
        [
            (
                "plan",
                blocks.ListBlock(
                    PlanCardBlock(),
                    icon="list-ul",
                ),
            )
        ],
        help_text="List of plans currently available.",
```

The `PlanCardBlock` is just a `StructBlock` with the plan's name, features and price:
```
class PlanCardBlock(blocks.StructBlock):
    title = blocks.CharBlock(required=True, help_text="Plan's title")
    description = blocks.TextBlock(required=True, help_text="Plan's description")
    unit_amount = blocks.DecimalBlock(min_value=0, max_value=100)
    features = blocks.ListBlock(blocks.CharBlock(label="Feature", icon="tick"))
```

Is there any extra setup I should do in order to have these fields to be translated?

**Comment by kaedroho** [comment] 2021-02-12 11:21
Thanks for reporting! I'm going to close this as it's duplicate of https://github.com/wagtail/wagtail-localize/issues/22

Wagtail Localize doesn't currently support `ListBlock` because there's no way to identify them and we might end up inserting translations into the wrong blocks.

For now, you can work around this by switching to a ``StreamBlock``.

**Closed by kaedroho** 2021-02-12 11:21 UTC

**Comment by MrCordeiro** [comment] 2021-02-12 11:41
Thanks for the heads up! :D
