### ISSUE TITLE
Disable translation for <code> tags.

### ISSUE THREAD

**Issue by Christophe-Gauge** [wagtail/wagtail-localize#581] opened 2022-05-29 16:55 UTC
I can't think of any reasons why sample code snippets between the `<code>...</code>` tags should ever be translated.

Is there a way to configure wagtail-localize to skip content between these tags when using automated translation?

**Comment by Christophe-Gauge** [comment] 2022-06-04 16:13
I am using https://pypi.org/project/wagtailcodeblock/ to add a "Code" content type to ContentStreamBlock.

Using automated translation with wagtail-localize, all "Code" blocks are translated:

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/6719029/172015251-31aac04e-db79-411f-bec3-9c15ab3c9f43.png">

**Comment by zerolab** [comment] 2022-06-05 11:23
Hey @Christophe-Gauge, thanks for the additional info.

This is very much what #307 aims to do. We'll get to it eventually (or if someone sponsors it, sooner)

Will close as duplicate of #307

**Closed by zerolab** 2022-06-05 11:23 UTC
