### ISSUE TITLE
500 error: saving page

### ISSUE THREAD

**Issue by onno-timmerman** [wagtail/wagtail-localize#322] opened 2021-02-12 09:04 UTC
An editor got the following 500 error. Not sure what the exact cause is.

**save_revisions() was called on a alias page. Revisions are not required on for alias pages as they are exact copy of another page**

**Comment by kaedroho** [comment] 2021-02-12 09:58
Hi @onno-timmerman 

This might have been [this Wagtail bug](https://github.com/wagtail/wagtail/issues/6758) that happens when you try to copy a page?

**Comment by onno-timmerman** [comment] 2021-02-12 16:43
Yes I think so its a bug in wagtail thx

I now finaly found out what happend.
1. Editor copy a page and select Alas
2. Editor select translates alias there the system asks what to translate and gives the error

When you want to translate wagtail offers all languages to translate.

It could be the editor first created the translation and then deleted this.

**Comment by kaedroho** [comment] 2021-02-19 09:12
There's definitely a separate bug there. When you create an alias in the same language, it shouldn't ask you to translate it. It should show the built-in Wagtail message to convert it into a regular page.

**Comment by ceelian** [comment] 2021-02-22 16:04
Might also be related/duplicate of this issue: https://github.com/wagtail/wagtail-localize/issues/298

**Closed** 2021-02-22 18:42 UTC
Labels: type:bug
