### ISSUE TITLE
`Sync Translations` on an unpublished page results in a 500 error.

### ISSUE THREAD

**Issue by TheBoroer** [wagtail/wagtail-localize#609] opened 2022-09-01 17:10 UTC
Hey all!
I ran into a weird issue where hitting sync translations on an unpublished page throws a 500 error in wagtail.
Anyone else run into this issue?

Steps to reproduce:
- Create an English page with a streamfield and blocks content & publish it
- Translate page to French & publish it
- Now go unpublish the English page
- Click `Sync Translations` on the english page and confirm (the state of the `publish immediately` checkbox doesn't make a difference, error happens for both cases)  
- bam! You should now see a 500 error

Here's the full traceback:

```
Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/wagtail/admin/urls/__init__.py", line 125, in wrapper
    return view_func(request, *args, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/wagtail/admin/auth.py", line 174, in decorated_view
    response = view_func(request, *args, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/wagtail_localize/views/update_translations.py", line 169, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/wagtail_localize/views/update_translations.py", line 123, in post
    return self.form_valid(form)
  File "/opt/python3.7/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/wagtail_localize/views/update_translations.py", line 130, in form_valid
    self.object.update_from_db()
  File "/opt/python3.7/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/wagtail_localize/models.py", line 480, in update_from_db
    self.refresh_segments()
  File "/opt/python3.7/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/wagtail_localize/models.py", line 562, in refresh_segments
    for segment in extract_segments(instance):
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/wagtail_localize/segments/extract.py", line 242, in extract_segments
    template, strings = extract_strings(field.value_from_object(instance))
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/wagtail_localize/strings.py", line 300, in extract_strings
    soup = BeautifulSoup(html, "html.parser")
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/bs4/__init__.py", line 310, in __init__
    elif len(markup) <= 256 and (
TypeError: object of type 'NoneType' has no len()
```

**Comment by zerolab** [comment] 2022-09-02 08:03
Thank you for the report @TheBoroer, this looks like a duplicate of #487, so will close in favour of that one

**Closed by zerolab** 2022-09-02 08:03 UTC
