### ISSUE TITLE
Translation not available for nested blocks in StreamField

### ISSUE THREAD

**Issue by ghost** [wagtail/wagtail-localize#355] opened 2021-03-01 06:23 UTC
I am using wagtail built-in translations system with wagtail_localize. For StreamFields with nested blocks, only first level block is available for translation.

Look at this example:

```
class Carousel(blocks.StructBlock):
  title = blocks.CharBlock(label='Titolo')
  text = blocks.RichTextBlock(label='Testo')
  items = blocks.ListBlock(blocks.StructBlock([
            ('tab_label', blocks.CharBlock(label='Testo visualizzato sulla tab')),
            ('title', blocks.CharBlock(label='Titolo')),
            ('text', blocks.RichTextBlock(label='Testo')),
            ('photo', ImageChooserBlock(label='Foto')),
            ('page', QuickPageLinkBlock(required=False)),
            ('color', NativeColorBlock(default="#085083", label = 'Colore per il titolo')),
        ]), label = 'Lista slide')
  
  class Meta:
    icon='snippet'
    label = 'Carosello'
    template = 'blocks/carousel.html'
```
Only title and text are available for translations (look at screenshot), but not all the items. I also need to translate items. How can i solve?
<img width="1544" alt="Schermata 2021-02-26 alle 11 44 16" src="https://user-images.githubusercontent.com/10153465/109459407-00de9100-7a5f-11eb-8da0-44ee97d3cebe.png">

**Comment by sabriinfo** [comment] 2021-03-01 07:56
I add, that also images and link within streamfield blocks or snippets are not translatable from admin.

<img width="980" alt="Schermata 2021-03-01 alle 08 55 27" src="https://user-images.githubusercontent.com/10153465/109467728-e959d500-7a6b-11eb-824b-7655a2ca3bf3.png">

**Comment by PhoenixKuzia** [comment] 2021-03-01 09:25
same issue.
That would be very nice to translate StreamFields with nested blocks.

**Comment by JeremyGibson** [comment] 2021-03-01 13:16
I think this is because you are nesting inside a ListBlock. This is a known issue. We got bit by this too. Best bet right now is to make the nesting structure a StreamField. https://github.com/wagtail/wagtail-localize/issues/22

**Comment by sabriinfo** [comment] 2021-03-02 08:45
Thanks @JeremyGibson 
However I see a lot of other problems:
- when I change models and migrate, every edit page for translated pages gives error 500. This seems to happen because segments to translate are saved to DB, and after migration those segments are not valid anymore. Am I right? Is there maybe a management command to correct all segments after migrations?
- using streamblocks instead of listblock allows translations, but for some reason while editing translated pages every field label has the name of the external field and not of the correct field (see screenshot)
<img width="1192" alt="Schermata 2021-03-02 alle 09 41 25" src="https://user-images.githubusercontent.com/10153465/109621622-80da2900-7b3b-11eb-8e6e-7db292ef30f1.png">
<img width="614" alt="Schermata 2021-03-02 alle 09 40 35" src="https://user-images.githubusercontent.com/10153465/109621630-833c8300-7b3b-11eb-9da1-ed4306701154.png">
- image and url fields in nested objects are not translatable. Only first level urls/page links are translatable.

Is there a solutions for these problems?
Otherwise I'm afraid I'll have to go back to wagtail_modeltranslation, hoping not to have too many problems in the transition.

**Comment by kaedroho** [comment] 2021-03-05 09:34
ListBlocks are currently not supported (see https://github.com/wagtail/wagtail-localize/issues/22). The current workaround is to switch these to StreamBlocks

**Comment by mexicat** [comment] 2021-03-15 15:31
I've also ran into this problem. If anyone needs it, I managed to convert an untranslatable `ListBlock` with type `gallery` (consisting of a list of `image` `StructBlock`s) into a translatable `StreamBlock` of type `gallery2` (with the same `image` `StructBlock`s) by running the following code after adding the `gallery2` definition to the model:

```python
for page in StaticPage.objects.all():
    new_body = []
    for b in enumerate(page.body.raw_data):
        if b['type'] == 'gallery':
            new_body.append({
                'type': 'gallery2',
                'value': [{'type': 'image', 'value': x} for x in b['value']]
            })
        else:
            new_body.append(b)

    page.body = json.dumps(new_body)
    page.save()
```

**Comment by krzysztofjeziorny** [comment] 2021-04-28 12:34
I'm converting a Wagtail site to use this app and came across a problem, that the raw html streamfields (and these are not `ListBlock`s) are not available for translation. Any idea what could cause it, or is it by design?

```python
class StreamfieldPage(Page):
    body = StreamField([
        ('heading', blocks.CharBlock(classname='full title')),
        ('paragraph', blocks.RichTextBlock()),
        ('raw', blocks.RawHTMLBlock()),
        ('static', blocks.StaticBlock()),
        ('image', ImageChooserBlock()),
    ])
    content_panels = Page.content_panels + [
        StreamFieldPanel('body'),
    ]
  …
```

**Comment by JeremyGibson** [comment] 2021-06-17 19:03
We are seeing this still on a current project.  We build almost everything as composable struct blocks that we then add into a page Streamfield.

`django==3.1.5`
`wagtail==2.12.3`
`wagtail-localize == v1.0rc2`

NOTE: We are seeing this behavior on both 0.9.5 and the release candidate

`blocks.py`

```
...
class HeroBlock(blocks.StructBlock):
    background_image = ImageChooserBlock(required=False)
    title = blocks.CharBlock(blank=True, required=False)
    description = blocks.RichTextBlock(
        features=BODY_ONLY_RICHTEXT_FEATURES, required=False
    )
    positioning = blocks.ChoiceBlock(
        choices=[("left", "Left"), ("center", "Center"), ("right", "Right"),],
        help_text="How title, description, and calls to action are aligned on the page.",
        required=True,
    )
    cta_buttons = CTAButtonsStreamBlock(required=False, blank=True, max_num=2)
    dark_background = blocks.BooleanBlock(
        required=False,
        initial=False,
        help_text="Guides choice of background color (if no background image) and text color",
    )
...
```
`models.py`
```
class GeneralContentPage(Page):
    body = StreamField(
        [
            ...
            ("hero", HeroBlock()),
            ...
         ]
```

**Source page**
![image](https://user-images.githubusercontent.com/2966242/122456830-fd263a00-cf7b-11eb-93f5-24b1c909eba4.png)

**Synced Translation Page**
![image](https://user-images.githubusercontent.com/2966242/122456976-25159d80-cf7c-11eb-8671-6b50f84e5e1e.png)

**Comment by kaedroho** [comment] 2021-11-02 12:59
The issue with translating `ImageChooserBlock` inside a `StructBlock` is now fixed by https://github.com/wagtail/wagtail-localize/pull/480

Looks like there's some other issues reported here. One of which is translating list blocks which is also reported [here](https://github.com/wagtail/wagtail-localize/issues/22) which is still an ongoing issue but should be solved soon

**Comment by zerolab** [comment] 2021-12-16 16:52
Everyone, can you please check the reported issues (aside from ListBlock) with wagtail-localize 1.0?

As far as I can summarise this #22 is the outstanding issue. If so, I'd move to close this issue.

@krzysztofjeziorny `RawHtmlBlock`s are not considered by design as who knows what content people add through them. May be worth opening a discussion for that, to see if there are enough compelling argumetns to make it translateable

**Comment by zerolab** [comment] 2022-06-01 12:03
Marking this as complete as we have nested block, and especially nested listblock support as of v1.1

**Closed by zerolab** 2022-06-01 12:03 UTC
