### ISSUE TITLE
"Synced translation" fails when image deleted.

### ISSUE THREAD

**Issue by alekseykret0v** [wagtail/wagtail-localize#825] opened 2024-09-10 10:30 UTC
Wagtail Localize supports "Synced translation" for page's translations.
![image](https://github.com/user-attachments/assets/fa21d917-8e97-4753-b368-4dbf5a70ef4b)

If someone deletes image used into any of "Synced translation" (e.g. click "Edit this image" and "DELETE IMAGE" then), it will be broken for this page.
![image](https://github.com/user-attachments/assets/3787fee2-c648-479c-93ca-93f6edf7a500)

**Comment by zerolab** [comment] 2024-09-10 11:04
Thank you for this @alekseykret0v 
Will close as a duplicate of #769.

**Closed by zerolab** 2024-09-10 11:04 UTC
